import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Footer from "@/sections/shared/Footer";
import Navbar from "@/components/shared/Navbar/Navbar";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400" , "700", "900"],
});

export const metadata: Metadata = {
  title: "Luminae",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} font-lato text-Grey-900 antialiased transition-[opacity,background,transform,filter] ease-in-out duration-400`}
      >
        <StoreProvider>
          <Navbar />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
